<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Phine - PHP Framework and CMS</title>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic|Lobster+Two:700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/foundation.css" />
    
    <link rel="stylesheet" href="foundation-icons/foundation-icons.css" />
    <link rel="stylesheet" href="Font-Awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="css/custom.css" />
    
</head>
<body>
    <div id="delete-modal" class="reveal-modal small" data-reveal="true">
        <h1><?php TransOut('Core.ModalDelete.Title')?></h1>
        <p>
            DELETE DESCRIPTION PLACEHOLDER
        </p>
        <form method="post">
            <input type="hidden" name="delete" id="modal-delete-field" />
            <a id="modal-delete-close" class="small secondary button"><?php TransOut('Core.ModalDelete.Cancel')?></a>
            <input type="submit" class="small button alert" value="<?php TransOut('Core.ModalDelete.Confirm')?>" />
        </form>
    </div>
    <header>
        <div class="row show-for-large-up">
            <div class="large-4 columns">
                <div id="logo">
                    <a href="#">Phine &CenterDot; CMS</a>
                </div>
            </div>
            <div class="large-8 columns">
            <nav id="top-nav">
                <ul class="inline-list Level_0 right">
                    <li><a href="#">Framework</a></li>
                        <li><a href="#">CMS</a></li>
                        <li><a href="#">Downloads</a></li>
                        <li><a href="#">Docs</a></li>
                  </ul>
            </nav>
            </div>
        </div>
        <div class="row show-for-medium-down">
            <div class="large-12 columns">
                <nav class="top-bar hide-for-large" data-topbar="data-topbar"  >
                <ul class="title-area">
                    <li class="name"><a href="#"><span><img src="img/logo.png" alt="Home" /></span></a></li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
                </ul>
                <section class="top-bar-section">
                    <ul class="Level_0 right">
                        <li><a href="#">Framework</a></li>
                        <li><a href="#">CMS</a></li>
                        <li><a href="">Download</a></li>
                        <li><a href="">Docs</a></li>
                    </ul>
                </section>
                </nav>
            </div>
        </div>
    </header>
    <div id="contents">
        <div class="row">
            
            <div class="large-12 columns">
                <div class="panel">
                    <form method="post">
                        <fieldset>
                            <legend><?php TransOut('Core.Login.Legend') ?></legend>
                        <?php if ($this->error):?>
                        <p class="alert-box alert">
                             <?php HtmlOut($this->error); ?>
                        </p>
                        <?php endif;?>
                        <label for="name">
                            <?php TransOut('Core.Login.Name')?>
                        </label>
                        <input id="name" type="text" name="Name" />
                        
                        <label for="password">
                            <?php TransOut('Core.Login.Password')?>
                        </label>
                        <input id="password" type="password" name="Password" />
                        </fieldset>
                        <input class="button" type="submit" value="<?php TransOut('Core.Login.Submit')?>">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="row">
            <div class="large-12 columns">
            <ul class="inline-list">
                <li>
                    <a href="#">Imprint</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
            </div>
        </div>
    </footer>
    
    <script src="js/vendor/modernizr.js"></script>
    <script src="js/vendor/jquery.js"></script>
    <script src="js/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>
</body>
</html>